# Generated by Django 4.2.7 on 2026-02-05 11:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contracted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('scope_description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('schedule_planned_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('at_risk', 'Под риском')], default='active', max_length=10)),
                ('discount_flag', models.BooleanField(default=False, verbose_name='Подозрение на демпинг')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('general_contractor', 'Генподрядчик'), ('subcontractor', 'Подрядчик')], max_length=20)),
                ('qualification_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('reliability_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_risk_flag', models.BooleanField(default=False)),
                ('nominated_from_above', models.BooleanField(default=False, verbose_name='Номинирован свыше')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('industrial', 'Промышленное'), ('residential', 'Жилое'), ('office', 'Офисное'), ('technopark', 'Технопарк')], max_length=20)),
                ('budget_planned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_contracted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('schedule_planned_start', models.DateField(blank=True, null=True)),
                ('schedule_planned_finish', models.DateField(blank=True, null=True)),
                ('schedule_actual_start', models.DateField(blank=True, null=True)),
                ('schedule_actual_finish', models.DateField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bank_covenants_status', models.CharField(choices=[('met', 'Соблюдены'), ('at_risk', 'Под риском'), ('violated', 'Нарушены')], default='met', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnitRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('industrial', 'Промышленное'), ('residential', 'Жилое'), ('office', 'Офисное'), ('technopark', 'Технопарк')], max_length=20)),
                ('work_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('rate_own_db', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate_market', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('own_db', 'Собственная БД'), ('market', 'Рыночная'), ('combined', 'Комбинированная')], default='own_db', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_file_ref', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('received', 'Получен'), ('under_review', 'На проверке'), ('accepted', 'Принят'), ('accepted_with_issues', 'Принят с замечаниями'), ('rejected', 'Отклонён')], default='received', max_length=20)),
                ('consistency_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('checked_by', models.CharField(blank=True, max_length=255)),
                ('processing_effort_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_flow_type', models.CharField(choices=[('advance', 'Аванс'), ('payment', 'Оплата'), ('retention', 'Удержание')], max_length=10)),
                ('source_system', models.CharField(choices=[('onec', '1С'), ('bitfinance', 'BitFinance'), ('manual', 'Ручной ввод')], default='manual', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.contract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('physical_volume_planned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('physical_volume_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_planned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='api.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.contractor'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.project'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('TOP_MANAGER', 'Топ-менеджер'), ('FIN_MANAGER', 'Финансовый менеджер'), ('SITE_MANAGER', 'Прораб'), ('PM', 'Руководитель проекта')], default='PM', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
